import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Hero from "@/components/hero";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Hero /> */}
      <body className={inter.className}>
        <Navbar mode="light" />
        <main className="relative overflow-hidden">{children}</main>
      </body>
    </html>
  );
}
